# Generated by Django 3.0.1 on 2020-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField()),
                ('make', models.CharField(max_length=120)),
                ('model', models.TextField()),
                ('rejection_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reason_1', models.TextField(blank=True, null=True)),
                ('reason_2', models.TextField(blank=True, null=True)),
                ('reason_3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
