# Generated by Django 3.0.1 on 2020-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rejection_percentage',
            field=models.CharField(max_length=3),
        ),
    ]
